from . import product_brand
from . import product_segment
from . import product_inherit
from . import sale_order_inherit
from . import driver
from . import product_attribute
from . import product_category
from . import product_sub_category
from . import stock_warehouse
from . import res_partner
